apiVersion: v1
data:
  cert_chain: /etc/certs/cert-chain.pem
  client_cert: /etc/certs/client-cert.pem
  client_key: /etc/certs/client-key.pem
  servername: istio.dev.nexmo.cloud
  upstream: istio-ingressgateway.istio-system.svc.cluster.local
kind: ConfigMap
metadata:
  labels:
    app: tlsproxy
    upstream: istio-dev
  name: istio-upstream-conf
  namespace: nexmo-k8s